fix: add the fixed Dockerfile for packaging iptables and generate the tarballs. It should pass with this commit.

diff --git a/scripts/packages/Dockerfile.iptables.qonq b/scripts/packages/Dockerfile.iptables.qonq
--- a/scripts/packages/Dockerfile.iptables.qonq
+++ b/scripts/packages/Dockerfile.iptables.qonq
@@ -41,25 +41,41 @@ apk add \
     libnetfilter_cttimeout \
     libnetfilter_queue \
 
+EOF
 
-if ! MODE="iptables-so" . /app/scripts/iptables-setup.sh; then
+# create the iptables musl-based shared objects tarball
+RUN <<EOF
+
+if ! (MODE="iptables-so" . /app/scripts/iptables-setup.sh); then
     printf "\n|> Error: could not execute the iptables-so function from the iptables-setup.sh shellscript. Exiting now...\n\n"
     return 1
 fi
 printf "\n|> Succesfully run iptables-so from iptables-setup.sh. Proceeding..."
 
+if ! (ls -allhtr "/app/iptables-so-pkg.tar.gz"); then
+    echo "|> SO TARBALL NOT FOUND. EXITING..."
+    return 1
+fi
+echo "|> FOUND THE SO TARBALL \O/ ...[PASSED]"
+
 EOF
 
-# set iptables binaries
+# create the iptables musl-based dynamically linked tarball
 RUN <<EOF
 
-if ! MODE="iptables-bin" . /app/scripts/iptables-setup.sh; then
+mkdir -p /app
+
+if ! (MODE="iptables-bin" . /app/scripts/iptables-setup.sh); then
     printf "\n|> Error: could not execute the iptables-bin function from the iptables-setup.sh shellscript. Exiting now...\n\n"
     return 1
 fi
 printf "\n|> Succesfully run iptables-bin from iptables-setup.sh. Proceeding..."
 
-
+if ! (ls -allhtr "/app/iptables-bin-pkg.tar.gz"); then
+    echo "|> BIN TARBALL NOT FOUND. EXITING..."
+    return 1
+fi
+echo "|> FOUND THE BIN TARBALL \O/ ...[PASSED]"
 
 EOF
 
@@ -67,6 +83,7 @@ EOF
 FROM alpine:3.22 AS relay
 
 WORKDIR /app/
-COPY --from=builder /iptables-pkg.tar.gz /iptables-pkg.tar.gz
+COPY --from=builder "/app/iptables-so-pkg.tar.gz" .
+COPY --from=builder "/app/iptables-bin-pkg.tar.gz" .
 
 ENTRYPOINT ["/bin/sh"]
