fix: [BREAKING] go back to the single tarball by leveraging apk-tools info option and doing the usual core_routine present on the newest ./scripts/packages/*-setup.sh; todo: copy --from=builder only one tarball gzipped instead of two.

diff --git a/scripts/packages/Dockerfile.podman.qonq b/scripts/packages/Dockerfile.podman.qonq
--- a/scripts/packages/Dockerfile.podman.qonq
+++ b/scripts/packages/Dockerfile.podman.qonq
@@ -6,42 +6,45 @@ WORKDIR /app
 # STEP 1
 RUN <<EOF
 apk upgrade && apk update && \
-#    apk add podman conmon runc crun
+    apk add podman conmon runc crun
+
+# (
+# cat <<HMM
+# http://dl-cdn.alpinelinux.org/alpine/edge/main
+# http://dl-cdn.alpinelinux.org/alpine/edge/community
+# http://dl-cdn.alpinelinux.org/alpine/edge/testing
+# HMM
+# ) > /etc/apk/repositories
 #
+# apk upgrade && apk update && \
+#     apk add podman crun
 
 
-
-
-(
-cat <<HMM
-http://dl-cdn.alpinelinux.org/alpine/edge/main
-http://dl-cdn.alpinelinux.org/alpine/edge/community
-http://dl-cdn.alpinelinux.org/alpine/edge/testing
-HMM
-) > /etc/apk/repositories
-
-apk upgrade && apk update && \
-    apk add podman crun
-
-
-if ! MODE="podman-so" . /app/scripts/podman-setup.sh; then
-    printf "\n|> Error: could not execute the podman-so function from the podman-setup.sh shellscript. Exiting now...\n\n"
+if ! MODE="podman-tarball" . /app/scripts/packages/podman-setup.sh; then
+    printf "\n|> Error: could not execute the podman-tarball function from the podman-setup.sh shellscript. Exiting now...\n\n"
     return 1
 fi
-printf "\n|> Succesfully run podman-so from podman-setup.sh. Proceeding..."
+printf "\n|> Succesfully run podman-tarball from podman-setup.sh. Proceeding..."
+
+
+## if ! MODE="podman-so" . /app/scripts/podman-setup.sh; then
+##     printf "\n|> Error: could not execute the podman-so function from the podman-setup.sh shellscript. Exiting now...\n\n"
+##     return 1
+## fi
+## printf "\n|> Succesfully run podman-so from podman-setup.sh. Proceeding..."
 
 EOF
 
 # set podman binaries
-RUN <<EOF
-
-if ! MODE="podman-bin" . /app/scripts/podman-setup.sh; then
-    printf "\n|> Error: could not execute the podman-bin function from the podman-setup.sh shellscript. Exiting now...\n\n"
-    return 1
-fi
-printf "\n|> Succesfully run podman-bin from podman-setup.sh. Proceeding..."
-
-EOF
+## RUN <<EOF
+##
+## if ! MODE="podman-bin" . /app/scripts/podman-setup.sh; then
+##     printf "\n|> Error: could not execute the podman-bin function from the podman-setup.sh shellscript. Exiting now...\n\n"
+##     return 1
+## fi
+## printf "\n|> Succesfully run podman-bin from podman-setup.sh. Proceeding..."
+##
+## EOF
 
 
 FROM alpine:3.22 AS relay
