fix: WARN FromAsCasing - [as] and [FROM] keywords casing did not matched at line 2 and 67. Setting all to uppercase at the Dockerfile.iptables.qonq

diff --git a/scripts/packages/Dockerfile.iptables.qonq b/scripts/packages/Dockerfile.iptables.qonq
--- a/scripts/packages/Dockerfile.iptables.qonq
+++ b/scripts/packages/Dockerfile.iptables.qonq
@@ -1,5 +1,7 @@
 #!/bin/sh
-FROM alpine:3.22 as builder
+FROM alpine:3.22 AS builder
+
+COPY ./scripts/packages/iptables-setup.sh /app/scripts/iptables-setup.sh
 
 WORKDIR /app
 # STEP 1
@@ -40,31 +42,29 @@ apk add \
     libnetfilter_queue \
 
 
+if ! MODE="iptables-so" . /app/scripts/iptables-setup.sh; then
+    printf "\n|> Error: could not execute the iptables-so function from the iptables-setup.sh shellscript. Exiting now...\n\n"
+    return 1
+fi
+printf "\n|> Succesfully run iptables-so from iptables-setup.sh. Proceeding..."
 
-# set IFS: input field separator
-IFS='\n\t'
+EOF
 
-# read each line defining the input field separator,
-# follow the soft link and append readlink output line to a new file
-while IFS= read -r line; do
-    readlink -f "$line" >> /bar.txt
-done < /foo.txt
+# set iptables binaries
+RUN <<EOF
 
-# remove new lines on the lists, then create new file
-sed '/^$/d' /foo.txt > /foobar.txt
-sed '/^$/d' /bar.txt >> /foobar.txt
+if ! MODE="iptables-bin" . /app/scripts/iptables-setup.sh; then
+    printf "\n|> Error: could not execute the iptables-bin function from the iptables-setup.sh shellscript. Exiting now...\n\n"
+    return 1
+fi
+printf "\n|> Succesfully run iptables-bin from iptables-setup.sh. Proceeding..."
 
-# then remove duplicate shared objects
-sort /foobar.txt | uniq > /quux.txt
-
-# generate a tarball of shared objects from filepaths on a text file
-tar -czf /iptables-pkg.tar.gz -T /quux.txt
 
 
 EOF
 
 
-FROM alpine:3.22 as relay
+FROM alpine:3.22 AS relay
 
 WORKDIR /app/
 COPY --from=builder /iptables-pkg.tar.gz /iptables-pkg.tar.gz
