fix: adjust dependencies and scopes for building qonq_bpftrace following the pattern used by qonq_podman

diff --git a/scripts/packages/Dockerfile.bpftrace.qonq b/scripts/packages/Dockerfile.bpftrace.qonq
--- a/scripts/packages/Dockerfile.bpftrace.qonq
+++ b/scripts/packages/Dockerfile.bpftrace.qonq
@@ -1,72 +1,47 @@
 FROM alpine:3.22 AS builder
 
-COPY ./scripts/packages/shadow-setup.sh /app/scripts/shadow-setup.sh
+COPY ./scripts/packages/bpftrace-setup.sh /app/scripts/bpftrace-setup.sh
+COPY ./scripts/packages/demo-replased.sh /app/scripts/packages/demo-replased.sh
 
 WORKDIR /app
 # STEP 1
 RUN <<EOF
 apk upgrade && apk update && \
-#    apk add shadow
+    apk add bpftrace
 
-(
-cat <<HMM
-http://dl-cdn.alpinelinux.org/alpine/edge/main
-http://dl-cdn.alpinelinux.org/alpine/edge/community
-http://dl-cdn.alpinelinux.org/alpine/edge/testing
-HMM
-) > /etc/apk/repositories
+# (
+# cat <<HMM
+# http://dl-cdn.alpinelinux.org/alpine/edge/main
+# http://dl-cdn.alpinelinux.org/alpine/edge/community
+# http://dl-cdn.alpinelinux.org/alpine/edge/testing
+# HMM
+# ) > /etc/apk/repositories
 
-apk upgrade && apk update && \
-    apk add busybox-binsh libbsd musl linux-pam shadow doas
+#apk upgrade && apk update && \
+#    apk add bpftrace
 
-
-if ! MODE="shadow-so" . /app/scripts/shadow-setup.sh; then
-    printf "\n|> Error: could not execute the shadow-so function from the shadow-setup.sh shellscript. Exiting now...\n\n"
+if ! MODE="bpftrace-tarball" . /app/scripts/packages/bpftrace-setup.sh; then
+    printf "\n|> Error: could not execute the bpftrace-tarball function from the bpftrace-setup.sh shellscript. Exiting now...\n\n"
     return 1
 fi
-printf "\n|> Succesfully run shadow-so from shadow-setup.sh. Proceeding..."
+printf "\n|> Succesfully run bpftrace-tarball from bpftrace-setup.sh. Proceeding..."
+
 
 EOF
-
-# set shadow binaries
-RUN <<EOF
-
-if ! MODE="shadow-bin" . /app/scripts/shadow-setup.sh; then
-    printf "\n|> Error: could not execute the shadow-bin function from the shadow-setup.sh shellscript. Exiting now...\n\n"
-    return 1
-fi
-printf "\n|> Succesfully run shadow-bin from shadow-setup.sh. Proceeding..."
-
-EOF
-
 
 FROM alpine:3.22 AS relay
 
-ARG SHADOW_SO_DIR="/app/shadow-shared-deps/"
-ARG SHADOW_BIN_DIR="/app/shadow/usr/bin/"
-
-ENV SHADOW_SO_DIR="/app/shadow-shared-deps/"
-ENV SHADOW_BIN_DIR="/app/shadow/usr/bin/"
 
 WORKDIR /app/
-RUN <<EOF
-mkdir -p "${SHADOW_SO_DIR}"
-mkdir -p "${SHADOW_BIN_DIR}"
-EOF
 
+# copy bpftrace dynamic linked binaries, shared objects and dotfiles/config-files
+COPY --from=builder "/bpftrace-tarball-pkg.tar.gz" /app
 
-# copy shadow shared objects
-COPY --from=builder "/shadow-so-pkg.tar.gz" /app
-
-# copy shadow binaries
-COPY --from=builder "/shadow-bin-pkg.tar.gz" /app
 
 RUN <<EOF
 
 ls -allhtr /app
 
-#ls -allhtr "${SHADOW_SO_DIR}"
-#ls -allhtr "${SHADOW_BIN_DIR}"
 EOF
 
 
