libkjx/beetor [4/n]
fix: adjust context for separate builds of libkjx/beetor_bwc

diff --git a/scripts/libkjx/Dockerfile.bwc b/scripts/libkjx/Dockerfile.bwc
--- a/scripts/libkjx/Dockerfile.bwc
+++ b/scripts/libkjx/Dockerfile.bwc
@@ -1,7 +1,7 @@
 # ==================
 # 1. Builder Step
 # ==================
-FROM alpine:3.20 as builder
+FROM alpine:3.22 AS builder
 
 COPY ./scripts/ /app/
 COPY ./assets/ /app/
@@ -14,7 +14,7 @@ apk upgrade && apk update && \
     apk add git musl-gcc openssl-dev \
       libcrypto zlib elfutils-dev
 
-LIBKJX_USER=beetor
+LIBKJX_USER=beetor_bwc
 
 # create user and group
 addgroup -g 1000 -S "${LIBKJX_USER}" && \
@@ -28,10 +28,35 @@ chown -R ${LIBKJX_USER}:${LIBKJX_USER} /home/${LIBKJX_USER}  && \
 
 su "${LIBKJX_USER}" -c "
 
-cd ~/app/
+cd /home/beetor_bwc/app/ || return
+
+MODE="bwc" . ./scripts/entrypoints/static_beetor.sh     > /home/beetor_bwc/app/foo-bwc.txt
 
 "
 EOF
+
+FROM alpine:3.22 AS relay
+
+WORKDIR /app
+
+COPY --from=builder /home/beetor_bwc/app/foo-bwc.txt    .
+
+RUN <<EOF
+
+ls -allhtr
+
+BWC="./foo-bwc.txt"
+
+if ! [ -f "${BWC}"]; then
+    printf "\n|> "${BWC}" was NOT found. Exiting now...\n\n"
+    exit
+fi && \
+
+printf "\n|> "${BWC}" found. Printing now...\n\n" && \
+cat "${BWC}" && \
+
+EOF
+
 
 # set command to be executed when the container starts
 ENTRYPOINT ["/bin/sh", "-c"]
@@ -40,5 +65,6 @@ ENTRYPOINT ["/bin/sh", "-c"]
 CMD ["apk upgrade && apk update &&
       apk add git musl-gcc openssl-dev \
       libcrypto zlib elfutils-dev && \
-      . /libkjx/static_beetor.sh"]
+      cd /app || return && \
+      MODE="builder" PROGRAM="bwc" . ./scripts/entrypoints/static_beetor.sh
 #CMD ["printf \"===== UNIT TEST =====\\n\\n\" && cat /tests/test_result.txt && printf \"\\n\\n===== UNIT COVERAGE =======\\n\\n\" && cat /tests/coverage_go.out && printf \"\\n\\n===== FUZZA =======\\n\\n\" && printf \"no-file-yet\""]
